### PR TITLE
Add generic github issue templates to the .github repository

### LINKED ISSUE #23: Add generic github issue templates for .github
### What needs to be done?
Add generic github issue templates to the .github repository to serve as default templates for the organization.

### PR DESCRIPTION
**Pull request by Zaperex**
### Description
Adds generic github issue templates to the .github repository
Additionally fixes the typo for the `ISSUE_TEMPLATES` directory

### What issue(s) does this fix?
Fixes #23

### CODE REVIEW

**Comment by kadel** [comment]
@Zaperex how does this work with templates defined in repos?

I noticed that for example https://github.com/janus-idp/backstage-plugins/tree/main/.github/ISSUE_TEMPLATE has some overlapping templates. Which one will be used?

**Comment by Zaperex** [comment]
These are just generic templates so edits can be made to tailor them to better suit the repositories they're placed in.
I'm assuming what you mean by "overlapping" templates, is when there's already an existing template (ex: bug report) in the repository that the generic template is trying to replace right?

**Review by tumido — COMMENTED** [review]
1. These are not issue templates for this repository only. Templates in the `.github` repository are shared with the whole organization and propagated to every repository. Is that the intention of this PR? Because the PR description states otherwise.
2. If the intention is to populate issue templates in this repository, what is the expectation from this repository content? `.github` repository is a special repository to GitHub and I would strongly advise against hosting source code in it. To my best knowledge this repository is not intended for hosting source code, therefore I have to ask, what is the purpose of all these issue templates? What Quality Assurance do we want to monitor here? What kind of Enhancements do we expect to be requested here? What of this repository content can contain bugs that can be discovered and reported?

Can you please clarify the intentions behind this PR and why it's relevant to this repository?

**Comment by Zaperex** [comment]
Ah I did not realize that the templates in the `.github` repository were shared throughout the whole organization. 
I made the PR with the assumption that it was a normal repository.

**Comment by Zaperex** [comment]
So based on some testing, I found that the `.github` repository's issue templates from the `.github/ISSUE_TEMPLATES` directory function as default/fallback issue templates for repositories without an existing `.github/ISSUE_TEMPLATES` directory. 

This means any repositories that already have templates defined would just ignore these templates and not be affected. 
Ex: `.github` repo has templates A, B, C and `repo-1` has templates D. When creating an issue in `repo-1`, only D would appear.

**Comment by Zaperex** [comment]
Since we already have all the templates we need in the repositories of interest, we currently do not need these common templates in the `.github` repository so I will close this PR for now.

**Pull request closed without merging**
